"""adding serial_number column to auth_refresh_tokens table

Revision ID: 2a9012cb369f
Revises: a2ae8edef417
Create Date: 2025-01-06 23:17:23.006663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9012cb369f'
down_revision: Union[str, None] = 'a2ae8edef417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_refresh_tokens', sa.Column('serial_number', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_refresh_tokens', 'serial_number')
    # ### end Alembic commands ###
