"""adding share_url and share_url_expires_at columns to Device

Revision ID: 5cd9d6732ce7
Revises: e3ca335ca356
Create Date: 2024-10-04 21:38:23.429277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd9d6732ce7'
down_revision: Union[str, None] = 'e3ca335ca356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('share_url', sa.String(length=255), nullable=True))
    op.add_column('device', sa.Column('share_url_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'share_url_expires_at')
    op.drop_column('device', 'share_url')
    # ### end Alembic commands ###
