"""Add id column and set unique constraints

Revision ID: 793faaf7296a
Revises: 96524a06cd64
Create Date: 2024-11-06 23:37:16.619396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793faaf7296a'
down_revision: Union[str, None] = '96524a06cd64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants_and_users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_unique_constraint('uix_tenant_user', 'tenants_and_users', ['tenant_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_tenant_user', 'tenants_and_users', type_='unique')
    op.drop_column('tenants_and_users', 'id')
    # ### end Alembic commands ###
