"""adding cascade rules for folder/subfolders

Revision ID: 83f46b609498
Revises: 96524a06cd64
Create Date: 2024-11-12 21:54:16.329338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f46b609498'
down_revision: Union[str, None] = '96524a06cd64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('folder_ibfk_3', 'folder', type_='foreignkey')
    op.create_foreign_key(None, 'folder', 'folder', ['parent_id'], ['id'], ondelete='cascade')
    op.drop_index('uix_tenant_user', table_name='tenants_and_users')
    op.create_foreign_key(None, 'tenants_and_users', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tenants_and_users', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants_and_users', type_='foreignkey')
    op.drop_constraint(None, 'tenants_and_users', type_='foreignkey')
    op.create_index('uix_tenant_user', 'tenants_and_users', ['tenant_id', 'user_id'], unique=True)
    op.drop_constraint(None, 'folder', type_='foreignkey')
    op.create_foreign_key('folder_ibfk_3', 'folder', 'folder', ['parent_id'], ['id'])
    # ### end Alembic commands ###
