"""initial

Revision ID: 8f3d97abb2b6
Revises: 
Create Date: 2024-09-15 19:38:59.353973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3d97abb2b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_AuthRefreshToken_created_by_id', 'auth_refresh_tokens', 'user', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_AuthRefreshToken_updated_by_id', 'auth_refresh_tokens', 'user', ['updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_Entity_created_by_id', 'entity', 'user', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_Entity_updated_by_id', 'entity', 'user', ['updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_Folder_created_by_id', 'folder', 'user', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_Folder_updated_by_id', 'folder', 'user', ['updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_Role_created_by_id', 'role', 'user', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_Role_updated_by_id', 'role', 'user', ['updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_Tag_created_by_id', 'tag', 'user', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_Tag_updated_by_id', 'tag', 'user', ['updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_Tenant_created_by_id', 'tenant', 'user', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_Tenant_updated_by_id', 'tenant', 'user', ['updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_User_created_by_id', 'user', 'user', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_User_updated_by_id', 'user', 'user', ['updated_by_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_User_updated_by_id', 'user', type_='foreignkey')
    op.drop_constraint('fk_User_created_by_id', 'user', type_='foreignkey')
    op.drop_constraint('fk_Tenant_updated_by_id', 'tenant', type_='foreignkey')
    op.drop_constraint('fk_Tenant_created_by_id', 'tenant', type_='foreignkey')
    op.drop_constraint('fk_Tag_updated_by_id', 'tag', type_='foreignkey')
    op.drop_constraint('fk_Tag_created_by_id', 'tag', type_='foreignkey')
    op.drop_constraint('fk_Role_updated_by_id', 'role', type_='foreignkey')
    op.drop_constraint('fk_Role_created_by_id', 'role', type_='foreignkey')
    op.drop_constraint('fk_Folder_updated_by_id', 'folder', type_='foreignkey')
    op.drop_constraint('fk_Folder_created_by_id', 'folder', type_='foreignkey')
    op.drop_constraint('fk_Entity_updated_by_id', 'entity', type_='foreignkey')
    op.drop_constraint('fk_Entity_created_by_id', 'entity', type_='foreignkey')
    op.drop_constraint('fk_AuthRefreshToken_updated_by_id', 'auth_refresh_tokens', type_='foreignkey')
    op.drop_constraint('fk_AuthRefreshToken_created_by_id', 'auth_refresh_tokens', type_='foreignkey')
    # ### end Alembic commands ###
