"""adding serialno column to device

Revision ID: 96524a06cd64
Revises: 5cd9d6732ce7
Create Date: 2024-10-17 10:35:03.307927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96524a06cd64'
down_revision: Union[str, None] = '5cd9d6732ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('serialno', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'device', ['serialno'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='unique')
    op.drop_column('device', 'serialno')
    # ### end Alembic commands ###
