"""updating not null attribute to SO_name and SO_version columns on device table

Revision ID: a2ae8edef417
Revises: c28c89e22f35
Create Date: 2025-01-06 10:26:58.111940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a2ae8edef417'
down_revision: Union[str, None] = 'c28c89e22f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'SO_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('device', 'SO_version',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'SO_version',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('device', 'SO_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
