"""deleting tenant's entity when deleting a tenant

Revision ID: accc0e39210c
Revises: bc2db54e7936
Create Date: 2025-04-03 16:06:07.257152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accc0e39210c'
down_revision: Union[str, None] = 'bc2db54e7936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenant_ibfk_1', 'tenant', type_='foreignkey')
    op.create_foreign_key(None, 'tenant', 'entity', ['entity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant', type_='foreignkey')
    op.create_foreign_key('tenant_ibfk_1', 'tenant', 'entity', ['entity_id'], ['id'])
    # ### end Alembic commands ###
