"""deleting heartbeat log entries when a device is deleted

Revision ID: bc2db54e7936
Revises: e524ce85652b
Create Date: 2025-04-01 17:10:41.461813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2db54e7936'
down_revision: Union[str, None] = 'e524ce85652b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('heartbeat_logs_ibfk_1', 'heartbeat_logs', type_='foreignkey')
    op.create_foreign_key(None, 'heartbeat_logs', 'device', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'heartbeat_logs', type_='foreignkey')
    op.create_foreign_key('heartbeat_logs_ibfk_1', 'heartbeat_logs', 'device', ['device_id'], ['id'])
    # ### end Alembic commands ###
