"""deleting tag when related tenant is deleted

Revision ID: d50178bd9502
Revises: accc0e39210c
Create Date: 2025-04-03 20:37:16.191033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50178bd9502'
down_revision: Union[str, None] = 'accc0e39210c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_ibfk_1', 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_foreign_key('tag_ibfk_1', 'tag', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
