"""removing heartbeat_timestamp column from device table

Revision ID: e318d3496d84
Revises: 1d389aa29576
Create Date: 2024-12-11 21:40:49.779911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e318d3496d84'
down_revision: Union[str, None] = '1d389aa29576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'heartbeat_timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('heartbeat_timestamp', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
