"""revisiting fk constraints for folder/entity/tags

Revision ID: e3ca335ca356
Revises: 035a665395c8
Create Date: 2024-09-16 15:15:09.679413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ca335ca356'
down_revision: Union[str, None] = '035a665395c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('folder_ibfk_1', 'folder', type_='foreignkey')
    op.create_foreign_key(None, 'folder', 'entity', ['entity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folder', type_='foreignkey')
    op.create_foreign_key('folder_ibfk_1', 'folder', 'entity', ['entity_id'], ['id'])
    # ### end Alembic commands ###
