"""removing is_online from device

Revision ID: e524ce85652b
Revises: cfd4a91c06b0
Create Date: 2025-02-18 13:15:05.815831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e524ce85652b'
down_revision: Union[str, None] = 'cfd4a91c06b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_is_online', table_name='device')
    op.drop_column('device', 'is_online')
    op.create_foreign_key('fk_TenantSettings_created_by_id', 'tenant_settings', 'user', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_TenantSettings_updated_by_id', 'tenant_settings', 'user', ['updated_by_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_TenantSettings_updated_by_id', 'tenant_settings', type_='foreignkey')
    op.drop_constraint('fk_TenantSettings_created_by_id', 'tenant_settings', type_='foreignkey')
    op.add_column('device', sa.Column('is_online', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('ix_device_is_online', 'device', ['is_online'], unique=False)
    # ### end Alembic commands ###
